app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_bundle_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api-rest-routing.yml"
    
fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }
            